routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'Front\frontController@index')->name('welcome');
Route::get('/artGallery', 'Front\frontController@artGalley')->name('art.gallery');
Route::get('/ourArtist', 'Front\frontController@ourArtist')->name('our.artist');
Route::get('/detailart/{id}', 'Front\frontController@detail')->name('art.detail');
Route::get('/artisdetail/{id}', 'Front\frontController@artisdetail')->name('artis.detail');

Route::post('/keranjangbeli', 'Front\frontController@keranjangbeli')->name('keranjangbeli');
Route::post('/postregister', 'Front\frontController@postregister')->name('post.register');
// Route::group(['middleware' => ['auth', 'CekRole:customer'], 'prefix' => 'Customer'], function () {
// 	Route::namespace('Front')->group(function () {
		
// 	});
// });

// Route::get('/registercompany', 'Auth\RegisterController@registercompany')->name('register.company');
// Route::get('/registerpersonal', 'Auth\RegisterController@registerpersonal')->name('register.personal');
// Route::post('postpersonal', 'Auth\RegisterController@postpersonal')->name('post.personal');
// Route::post('postcompany', 'Auth\RegisterController@postcompany')->name('post.company');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/province','Front\rajaOngkirController@get_province')->name('province');
Route::get('/kota/{id}','Front\rajaOngkirController@get_city')->name('city');
Route::get('/origin={city_origin}&destination={city_destination}&weight={weight}&courier={courier}','Front\rajaOngkirController@get_ongkir')->name('ongkir');


// Route::get('/cekkabupaten', 'Front\rajaOngkirController@index');



Route::group(['middleware' => ['auth', 'CekRole:customercompany,customerpersonal']], function () {
	Route::get('/MyDashboardPersonal', 'Front\customerController@index')->name('dashboard.customer');
	Route::get('/MyTransaksiPersonal', 'Front\customerController@tbelipersonal')->name('transaksi.beli.p');
	Route::get('/SettingAkun', 'Front\customerController@settingakunp')->name('setting.akun.p');

	// transaksi
	Route::get('/ListKeranjang', 'Front\transaksiController@listkeranjangbeli')->name('listkeranjang');
	Route::get('/hapuscart/{key}', 'Front\transaksiController@hapuscart')->name('hapus.cart');
	Route::post('/ProsesBeli', 'Front\transaksiController@prosesbeli')->name('proses.orderbeli');
});

Route::group(['middleware' => ['auth', 'CekRole:superadmin'], 'prefix' => 'Superadmin'], function () {
	Route::namespace('Superadmin')->group(function () {
		Route::resource('kategoriproduk', 'kategoriProdukController');
		Route::resource('produk', 'produkController');
		Route::resource('pelukis', 'pelukisController')->parameters(['pelukis' => 'pelukis',]);
		Route::resource('ongkir', 'ongkirController');
		Route::resource('voucher', 'voucherController');
		Route::get('TransaksiBeli', 'TransaksiBeli@index')->name('t.beli.s');
		Route::get('KonfirmasiBeli/{id}', 'TransaksiBeli@konfirmasiBeli')->name('konfirmasi.beli');
	});
});

// run artisan command
Route::get('/artisan', function () {
	Artisan::call('config:cache');
	Artisan::call('config:clear');
	Artisan::call('route:clear');
	Artisan::call('cache:clear');
	return 'OK';
 });

app/Ongkir.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ongkir extends Model
{
    protected $fillable = [
        'kabupaten',
        'tarif',
    ];
}

app/Http/Controllers/Superadmin/TransaksiBeli.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Produk;
use App\ReservasiBeli;
use Illuminate\Http\Request;

class TransaksiBeli extends Controller
{
    public function index()
    {
        $data = ReservasiBeli::with('detailbeli')->get();
        // dd($data);
        return view('Superadmin.Transaksi.index', compact('data'));
    }

    public function konfirmasiBeli($id)
    {
        $data = ReservasiBeli::with('detailbeli')->find($id);
        $data->update([
            'statuspembayaran' => 'Terbayar'
        ]);
        foreach($data['detailbeli'] as $p)
        {
            $produk = Produk::find($p->id);
            $produk->update([
                'status' => 'terjual',
            ]);
        }
        toast('Data Beli Berhasil Dikonfirmasi','success');
        return redirect()->back();
    }
}

app/Http/Controllers/Superadmin/kategoriProdukController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Superadmin\KategoriProduk\KategoriProdukCreate;
use App\Http\Requests\Superadmin\KategoriProduk\KategoriProdukUpdate;
use App\KategoriProduk;
use App\Produk;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class kategoriProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = KategoriProduk::paginate(10);
        return view('Superadmin.KategoriProduk.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KategoriProdukCreate $request)
    {
        $data = $request->all();
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'kategori' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Kategori/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        KategoriProduk::create($data);
        toast('Data Kategori Di Tambahkan','success');
        return redirect()->route('kategoriproduk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(KategoriProduk $kategoriproduk)
    {
        return view('Superadmin.KategoriProduk.edit', compact('kategoriproduk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KategoriProdukUpdate $request, KategoriProduk $kategoriproduk)
    {
        $data = $request->all();
        $data['foto'] = $kategoriproduk->foto;
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'kategori' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Kategori/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        $kategoriproduk->update($data);
        toast('Data Kategori Di Update','success');
        return redirect()->route('kategoriproduk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(KategoriProduk $kategoriproduk)
    {
        $cek = Produk::where('kategori_id', $kategoriproduk->id)->first();
        if(isset($cek)){
            alert()->info('Info','Data Kategori Di Gunakan Pada Produk');
            return redirect()->route('kategoriproduk.index');
        }
        $kategoriproduk->delete();
        toast('Data Kategori Di Hapus','error');
        return redirect()->route('kategoriproduk.index');
    }
}

app/Http/Controllers/Superadmin/ongkirController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Ongkir\ongkirRequestCU;
use App\Ongkir;
use Illuminate\Http\Request;

class ongkirController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Ongkir::paginate(10);
        return view('Superadmin.Ongkir.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ongkirRequestCU $request)
    {
        $data = $request->all();
        Ongkir::create($data);
        toast('Data Ongkir Di Tambahkan','success');
        return redirect()->route('ongkir.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Ongkir $ongkir)
    {
        return view('Superadmin.Ongkir.edit', compact('ongkir'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ongkirRequestCU $request, Ongkir $ongkir)
    {
        $data = $request->all();
        $ongkir->update($data);
        toast('Data Ongkir Di Update','success');
        return redirect()->route('ongkir.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ongkir $ongkir)
    {
        $ongkir->delete();
        toast('Data Ongkir Di Hapus','error');
        return redirect()->route('ongkir.index');
    }
}

app/Http/Controllers/Superadmin/pelukisController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Superadmin\Pelukis\pelukisCreate;
use App\Http\Requests\Superadmin\Pelukis\pelukisUpdate;
use App\Pelukis;
use App\Produk;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class pelukisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Pelukis::paginate(10);
        return view('Superadmin.Pelukis.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Superadmin.Pelukis.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(pelukisCreate $request)
    {
        $data = $request->all();
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'kategori' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Kategori/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        Pelukis::create($data);
        toast('Data Pelukis Di Tambahkan','success');
        return redirect()->route('pelukis.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Pelukis $pelukis)
    {
        return view('Superadmin.Pelukis.edit', compact('pelukis'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(pelukisUpdate $request, Pelukis $pelukis)
    {
        $data = $request->all();
        $data['foto'] = $pelukis->foto;
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'kategori' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Kategori/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        $pelukis->update($data);
        toast('Data Pelukis Di Update','success');
        return redirect()->route('pelukis.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pelukis $pelukis)
    {
        $cek = Produk::where('pelukis_id', $pelukis->id)->first();
        if(isset($cek)){
            alert()->info('Info','Data Pelukis Di Gunakan Pada Produk');
            return redirect()->route('pelukis.index');
        }
        $pelukis->delete();
        toast('Data Pelukis Di Hapus','error');
        return redirect()->route('pelukis.index');
    }
}

app/Http/Controllers/Superadmin/produkController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Superadmin\Produk\createProduk;
use App\Http\Requests\Superadmin\Produk\updateProduk;
use App\KategoriProduk;
use App\Pelukis;
use App\Produk;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class produkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Produk::with(['pelukis'])->paginate(10);
        // dd($data);
        return view('Superadmin.Produk.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = KategoriProduk::get();
        $pelukis = Pelukis::get();
        return view('Superadmin.Produk.create', compact('kategori', 'pelukis'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(createProduk $request)
    {
        $data = $request->all();
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'produk' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Produk/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        // $data['status'] = 'tersedia';
        Produk::create($data);
        toast('Data Produk Di Tambahkan','success');
        return redirect()->route('produk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Produk $produk)
    {
        $kategori = KategoriProduk::get();
        $pelukis = Pelukis::get();
        return view('Superadmin.Produk.edit', compact('produk', 'kategori', 'pelukis'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateProduk $request, Produk $produk)
    {
        $data = $request->all();
        $data['foto'] = $produk->foto;
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'produk' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Produk/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        $produk->update($data);
        toast('Data Produk Di Update','success');
        return redirect()->route('produk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Superadmin/Ongkir/edit.blade.php
@extends('layouts.stisla')

@section('content')
<div class="main-content">
    <div class="row justify-content-center">
        <div class="col-md-10 ml-5">
              <div class="row">
                <div class="col-md-12 text-center">
                    @foreach ($errors->all() as $error)
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ $error }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endforeach
                </div>
              </div>
          <div class="card">
            <div class="card-header">
                <h4>Ubah Data {{ $ongkir->kabupaten }}</h4>
            </div>
            <div class="card-body">
             <form action="{{ route('ongkir.update', $ongkir) }}" method="POST">
                 @csrf
                 @method('PUT')
                 <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Kabupaten</label>
                    <input type="text" class="form-control" name="kabupaten" placeholder="Nama Kabupaten" value="{{ old('kabupaten', $ongkir->kabupaten) }}">
                  </div>
                
                  <label for="exampleFormControlInput1" class="form-label">Tarif</label>
                  <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Rp</span>
                    <input type="number" name="tarif" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder="tarif" value="{{ old('tarif', $ongkir->tarif) }}">
                  </div>
                  
                 <div class="col-md-12 mb-5 text-center">
                     <button class="btn btn-primary">Simpan</button>
                 </div>
             </form>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/Superadmin/Ongkir/index.blade.php
@extends('layouts.stisla')

@section('content')
<div class="main-content">
    <div class="row">
        <div class="col-md-7 card">
            <div class="card-header">
                <h4>Semua Data Ongkir</h4>
            </div>
            <div class="card-body">
                <table class="table text-center table-hover">
                    <thead>
                      <tr>
                        <th scope="col">No</th>
                        <th scope="col">Kabupaten</th>
                        <th scope="col">Tarif</th>
                        <th scope="col">Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                        @forelse ($data as $item => $ongkir)
                            <tr>
                                <th scope="row">{{ $data->firstItem() + $item }}</th>
                                <td>{{ $ongkir->kabupaten }}</td>
                                <td>
                                    Rp {{ number_format($ongkir->tarif) }}
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <b><i class="fas fa-ellipsis-v"></i></b>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a href="{{ route('ongkir.edit', $ongkir) }}" class="dropdown-item">Edit</a>
                                            <form action="{{ route('ongkir.destroy', $ongkir) }}" method="POST" onsubmit="return confirm('Hapus Data, Anda Yakin ?')">
                                                {!! method_field('delete') . csrf_field() !!}
                                                <button class="dropdown-item" type="submit">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                </td>
                            </tr>
                        @empty
                            
                        @endforelse
                     
                    </tbody>
                  </table>
            </div>
        </div>
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-12 text-center">
                    @foreach ($errors->all() as $error)
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ $error }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endforeach
                </div>
            </div>
          <div class="card">
            <div class="card-header">
                <h4>Tambah Data Ongkir</h4>
            </div>
            <div class="card-body">
             <form action="{{ route('ongkir.store') }}" method="POST">
                 @csrf
                 <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Kabupaten</label>
                    <input type="text" class="form-control" name="kabupaten" placeholder="nama kabupaten" value="{{ old('kabupaten') }}">
                  </div>

                  <label for="exampleFormControlInput1" class="form-label">Tarif</label>
                  <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Rp</span>
                    <input type="number" name="tarif" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder="tarif" value="{{ old('tarif') }}">
                  </div>

                 <div class="col-md-12 mb-5 text-center">
                     <button class="btn btn-primary">Simpan</button>
                 </div>
             </form>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection